# kubernetes/02-postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cryptolink-app
type: Opaque
stringData:
  # WAŻNE: Te wartości zostaną nadpisane przez sekrety z GitHub Actions
  # podczas wdrożenia przez pipeline CI/CD.
  POSTGRES_USER: "azureuser"
  POSTGRES_PASSWORD: "your-postgres-password" 