# kubernetes/06-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cryptolink-app-service
  namespace: cryptolink-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cryptolink-app