# kubernetes/07-ingress.yaml
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: cryptolink-ingress
#  namespace: cryptolink-app
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
# - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: cryptolink-app-service
#            port:
#              number: 80